<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="InicioTenant-20231211193850" tests="1" file=".py" time="7.020" timestamp="2023-12-11T19:38:57" failures="0" errors="1" skipped="0">
	<testcase classname="InicioTenant" name="test_inicio_tenant" time="7.020" timestamp="2023-12-11T19:38:57" file="inicio.py" line="29">
		<error type="AttributeError" message="'str' object has no attribute 'find_element'"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\inicio.py", line 31, in test_inicio_tenant
    self.login_helper.login("admingd@silohub.ag", "G@viglio123")
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\loginhelper.py", line 10, in login
    user = find_element_by_id(self.driver, "email")
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\findElements.py", line 9, in find_element_by_id
    return WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, id)))
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\support\wait.py", line 92, in until
    value = method(self._driver)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\support\expected_conditions.py", line 80, in _predicate
    return driver.find_element(*locator)
AttributeError: 'str' object has no attribute 'find_element'
]]></error>
	</testcase>
</testsuite>
