<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Onboarding_test_tenant-20231219170527" tests="2" file=".py" time="3.432" timestamp="2023-12-19T17:05:30" failures="0" errors="2" skipped="0">
	<testcase classname="Onboarding_test_tenant" name="test_tenat_onboarding" time="0.000" timestamp="0001-01-01T00:00:00" file="Onboarding.py" line="27">
		<error type="AttributeError" message="module 'lib2to3.pgen2.driver' has no attribute 'find_element'"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Onboarding.py", line 29, in test_tenat_onboarding
    self.login_Sample.login("luis.tacourt@gmail.com", "Bet$123456")
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\LoginSample.py", line 10, in login
    user = find_element_by_id(self.driver, "email")  # asegÃºrate de pasar self.driver
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\findElements.py", line 10, in find_element_by_id
    return WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, id)))
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\support\wait.py", line 92, in until
    value = method(self._driver)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\support\expected_conditions.py", line 80, in _predicate
    return driver.find_element(*locator)
AttributeError: module 'lib2to3.pgen2.driver' has no attribute 'find_element'
]]></error>
	</testcase>
	<testcase classname="Onboarding_test_tenant" name="test_tenat_onboarding" time="3.432" timestamp="2023-12-19T17:05:30" file="Onboarding.py" line="27">
		<error type="AttributeError" message="'Onboarding_test_tenant' object has no attribute 'driver'"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Onboarding.py", line 477, in tearDown
    self.driver.quit()
AttributeError: 'Onboarding_test_tenant' object has no attribute 'driver'
]]></error>
	</testcase>
</testsuite>
