<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="HomeTenant-20240510164251" tests="1" file=".py" time="7.346" timestamp="2024-05-10T16:42:58" failures="0" errors="1" skipped="0">
	<testcase classname="HomeTenant" name="test_start_tenant" time="7.346" timestamp="2024-05-10T16:42:58" file="Home.py" line="19">
		<error type="NoSuchWindowException" message="Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.156)
Stacktrace:
	GetHandleVerifier [0x00007FF7F3371562+60802]
	(No symbol) [0x00007FF7F32EAC62]
	(No symbol) [0x00007FF7F31A7CE4]
	(No symbol) [0x00007FF7F317DFDF]
	(No symbol) [0x00007FF7F3221E57]
	(No symbol) [0x00007FF7F32398D1]
	(No symbol) [0x00007FF7F321A923]
	(No symbol) [0x00007FF7F31E8FEC]
	(No symbol) [0x00007FF7F31E9C21]
	GetHandleVerifier [0x00007FF7F36741FD+3217949]
	GetHandleVerifier [0x00007FF7F36B6197+3488183]
	GetHandleVerifier [0x00007FF7F36AF11F+3459391]
	GetHandleVerifier [0x00007FF7F342B926+823622]
	(No symbol) [0x00007FF7F32F5FFF]
	(No symbol) [0x00007FF7F32F0F24]
	(No symbol) [0x00007FF7F32F10B2]
	(No symbol) [0x00007FF7F32E1904]
	BaseThreadInitThunk [0x00007FFEC3DD257D+29]
	RtlUserThreadStart [0x00007FFEC4CAAA48+40]
"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Home.py", line 21, in test_start_tenant
    self.login_helper.login("admingd@silohub.ag", "G@viglio123")
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Loginhelper.py", line 9, in login
    user = find_element_by_id(self.driver, "email")  # asegÃºrate de pasar self.driver
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\FindElements.py", line 10, in find_element_by_id
    return WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, id)))
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\support\expected_conditions.py", line 84, in _predicate
    return driver.find_element(*locator)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 742, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.156)
Stacktrace:
	GetHandleVerifier [0x00007FF7F3371562+60802]
	(No symbol) [0x00007FF7F32EAC62]
	(No symbol) [0x00007FF7F31A7CE4]
	(No symbol) [0x00007FF7F317DFDF]
	(No symbol) [0x00007FF7F3221E57]
	(No symbol) [0x00007FF7F32398D1]
	(No symbol) [0x00007FF7F321A923]
	(No symbol) [0x00007FF7F31E8FEC]
	(No symbol) [0x00007FF7F31E9C21]
	GetHandleVerifier [0x00007FF7F36741FD+3217949]
	GetHandleVerifier [0x00007FF7F36B6197+3488183]
	GetHandleVerifier [0x00007FF7F36AF11F+3459391]
	GetHandleVerifier [0x00007FF7F342B926+823622]
	(No symbol) [0x00007FF7F32F5FFF]
	(No symbol) [0x00007FF7F32F0F24]
	(No symbol) [0x00007FF7F32F10B2]
	(No symbol) [0x00007FF7F32E1904]
	BaseThreadInitThunk [0x00007FFEC3DD257D+29]
	RtlUserThreadStart [0x00007FFEC4CAAA48+40]

]]></error>
	</testcase>
</testsuite>
