<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="HomeTenant-20240112114749" tests="1" file=".py" time="31.618" timestamp="2024-01-12T11:48:20" failures="1" errors="0" skipped="0">
	<testcase classname="HomeTenant" name="test_start_tenant" time="31.618" timestamp="2024-01-12T11:48:20" file="Home.py" line="22">
		<failure type="AssertionError" message=""><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Home.py", line 52, in test_start_tenant
    validate_text(self.driver, page_hello, desired_text  )
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Elements.py", line 187, in validate_text
    assert texto_obtenido == texto_esperado
AssertionError
]]></failure>
		<system-out><![CDATA[¡Botón encontrado y clickeado con éxito!
¡Botón encontrado y clickeado con éxito!
¡Botón encontrado y clickeado con éxito!
¡Botón encontrado y clickeado con éxito!
El texto es visible para el usuario
]]></system-out>
	</testcase>
</testsuite>
