<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="CtaContOperSecundaria.contrato_operSecundarias-20240423154315" tests="1" file="CtaContOperSecundaria.py" time="6.322" timestamp="2024-04-23T15:43:21" failures="0" errors="1" skipped="0">
	<testcase classname="CtaContOperSecundaria.contrato_operSecundarias" name="test_contratc_oparSecondary" time="6.322" timestamp="2024-04-23T15:43:21" file="CtaContOperSecundaria.py" line="22">
		<error type="NoSuchWindowException" message="Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.61)
Stacktrace:
	GetHandleVerifier [0x00007FF793CDF922+3045234]
	(No symbol) [0x00007FF793983652]
	(No symbol) [0x00007FF793847564]
	(No symbol) [0x00007FF79381DB4F]
	(No symbol) [0x00007FF7938C1087]
	(No symbol) [0x00007FF7938D8871]
	(No symbol) [0x00007FF7938B9B53]
	(No symbol) [0x00007FF79388813C]
	(No symbol) [0x00007FF793888D71]
	GetHandleVerifier [0x00007FF793D0E89D+3237613]
	GetHandleVerifier [0x00007FF793D50BA7+3508727]
	GetHandleVerifier [0x00007FF793D4976F+3478975]
	GetHandleVerifier [0x00007FF793ABF1C6+815126]
	(No symbol) [0x00007FF79398ED0F]
	(No symbol) [0x00007FF793989854]
	(No symbol) [0x00007FF7939899E2]
	(No symbol) [0x00007FF79397A574]
	BaseThreadInitThunk [0x00007FF834EC257D+29]
	RtlUserThreadStart [0x00007FF835A2AA48+40]
"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\CtaContOperSecundaria.py", line 24, in test_contratc_oparSecondary
    self.login_helper.login("admingd@silohub.ag", "G@viglio123")
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Loginhelper.py", line 9, in login
    user = find_element_by_id(self.driver, "email")  # asegÃºrate de pasar self.driver
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\FindElements.py", line 10, in find_element_by_id
    return WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, id)))
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\support\expected_conditions.py", line 84, in _predicate
    return driver.find_element(*locator)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 742, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.61)
Stacktrace:
	GetHandleVerifier [0x00007FF793CDF922+3045234]
	(No symbol) [0x00007FF793983652]
	(No symbol) [0x00007FF793847564]
	(No symbol) [0x00007FF79381DB4F]
	(No symbol) [0x00007FF7938C1087]
	(No symbol) [0x00007FF7938D8871]
	(No symbol) [0x00007FF7938B9B53]
	(No symbol) [0x00007FF79388813C]
	(No symbol) [0x00007FF793888D71]
	GetHandleVerifier [0x00007FF793D0E89D+3237613]
	GetHandleVerifier [0x00007FF793D50BA7+3508727]
	GetHandleVerifier [0x00007FF793D4976F+3478975]
	GetHandleVerifier [0x00007FF793ABF1C6+815126]
	(No symbol) [0x00007FF79398ED0F]
	(No symbol) [0x00007FF793989854]
	(No symbol) [0x00007FF7939899E2]
	(No symbol) [0x00007FF79397A574]
	BaseThreadInitThunk [0x00007FF834EC257D+29]
	RtlUserThreadStart [0x00007FF835A2AA48+40]

]]></error>
	</testcase>
</testsuite>
