<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="contrato_tenant-20240130130805" tests="1" file=".py" time="7.302" timestamp="2024-01-30T13:08:13" failures="0" errors="1" skipped="0">
	<testcase classname="contrato_tenant" name="test_contrato_tenant" time="7.302" timestamp="2024-01-30T13:08:13" file="Cuentacontrato.py" line="22">
		<error type="NoSuchWindowException" message="Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=121.0.6167.86)
Stacktrace:
	GetHandleVerifier [0x00007FF7D50D5E42+3538674]
	(No symbol) [0x00007FF7D4CF4C02]
	(No symbol) [0x00007FF7D4BA5AEB]
	(No symbol) [0x00007FF7D4B8288C]
	(No symbol) [0x00007FF7D4C15DD7]
	(No symbol) [0x00007FF7D4C2B40F]
	(No symbol) [0x00007FF7D4C0EE53]
	(No symbol) [0x00007FF7D4BDF514]
	(No symbol) [0x00007FF7D4BE0631]
	GetHandleVerifier [0x00007FF7D5106CAD+3738973]
	GetHandleVerifier [0x00007FF7D515C506+4089270]
	GetHandleVerifier [0x00007FF7D5154823+4057299]
	GetHandleVerifier [0x00007FF7D4E25C49+720121]
	(No symbol) [0x00007FF7D4D0126F]
	(No symbol) [0x00007FF7D4CFC304]
	(No symbol) [0x00007FF7D4CFC432]
	(No symbol) [0x00007FF7D4CEBD04]
	BaseThreadInitThunk [0x00007FFD3501257D+29]
	RtlUserThreadStart [0x00007FFD3684AA58+40]
"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Cuentacontrato.py", line 24, in test_contrato_tenant
    self.login_helper.login("admingd@silohub.ag", "G@viglio123")
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\loginhelper.py", line 10, in login
    user = find_element_by_id(self.driver, "email")  # asegÃºrate de pasar self.driver
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\findElements.py", line 10, in find_element_by_id
    return WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, id)))
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\support\expected_conditions.py", line 84, in _predicate
    return driver.find_element(*locator)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 742, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=121.0.6167.86)
Stacktrace:
	GetHandleVerifier [0x00007FF7D50D5E42+3538674]
	(No symbol) [0x00007FF7D4CF4C02]
	(No symbol) [0x00007FF7D4BA5AEB]
	(No symbol) [0x00007FF7D4B8288C]
	(No symbol) [0x00007FF7D4C15DD7]
	(No symbol) [0x00007FF7D4C2B40F]
	(No symbol) [0x00007FF7D4C0EE53]
	(No symbol) [0x00007FF7D4BDF514]
	(No symbol) [0x00007FF7D4BE0631]
	GetHandleVerifier [0x00007FF7D5106CAD+3738973]
	GetHandleVerifier [0x00007FF7D515C506+4089270]
	GetHandleVerifier [0x00007FF7D5154823+4057299]
	GetHandleVerifier [0x00007FF7D4E25C49+720121]
	(No symbol) [0x00007FF7D4D0126F]
	(No symbol) [0x00007FF7D4CFC304]
	(No symbol) [0x00007FF7D4CFC432]
	(No symbol) [0x00007FF7D4CEBD04]
	BaseThreadInitThunk [0x00007FFD3501257D+29]
	RtlUserThreadStart [0x00007FFD3684AA58+40]

]]></error>
	</testcase>
</testsuite>
