<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="finanzas_cobro-20240411181757" tests="1" file=".py" time="33.935" timestamp="2024-04-11T18:18:31" failures="0" errors="1" skipped="0">
	<testcase classname="finanzas_cobro" name="test_finance_payment" time="33.935" timestamp="2024-04-11T18:18:31" file="FinanzasCobro.py" line="23">
		<error type="AttributeError" message="'str' object has no attribute 'find_element'"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\FinanzasCobro.py", line 57, in test_finance_payment
    clear_and_send_keys(insert_amount,value_amount, self.driver)
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Elements.py", line 806, in clear_and_send_keys
    field_element = WebDriverWait(driver, 10).until(
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\support\expected_conditions.py", line 363, in _predicate
    target = driver.find_element(*target)  # grab element at locator
AttributeError: 'str' object has no attribute 'find_element'
]]></error>
	</testcase>
</testsuite>
